config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'fetch' => 'main#fetch'
  post 'submission' => 'main#submission'
  post 'submission_from_app' => 'main#organization_form_submission'
  root to: 'main#home'
end

app/models/admin.rb
# == Schema Information
#
# Table name: admins
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable


end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Category < ActiveRecord::Base

  has_many :organizations

  validates :name, presence: true

end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id                :integer          not null, primary key
#  name              :string(255)
#  website           :string(255)
#  description       :string(255)
#  logo_file_name    :string(255)
#  logo_content_type :string(255)
#  logo_file_size    :integer
#  logo_updated_at   :datetime
#  address           :string(255)
#  latitude          :float(24)
#  longitude         :float(24)
#  founded_in        :integer
#  approved          :boolean
#  submitter_email   :string(255)
#  submitter_name    :string(255)
#  category_id       :integer
#  created_at        :datetime
#  updated_at        :datetime
#
require 'open-uri'

class Organization < ActiveRecord::Base
  belongs_to :category
  acts_as_taggable

  validates :name, :address, presence: true
  validates :approved, inclusion: { in: [true, false] }
  validates :submitter_email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, allow_blank: true
  validates :website, uniqueness: true, allow_blank: true

  has_attached_file :logo, styles: { thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment :logo, content_type: { content_type: /\Aimage\/.*\Z/ }, size: { in: 0..1.megabytes }

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def logo_url=(url)
    unless url.blank?
      begin
        self.logo = URI.parse(URI.encode(url)) rescue nil
      rescue
        p "issue processing #{url}"
      end
    end
  end

  def logo_json_url
    logo.url(:thumb)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:organization_form_submission]
  def home
    @organization = Organization.new
    render layout: nil
  end

  def fetch
    @organizations = Organization.where(approved: true).order('name asc').paginate(page: params[:page], per_page: 150)
    render json: @organizations.to_json(include: [:category], methods: [:logo_json_url])
  end

  def submission
    @organization = Organization.new
    @organization.name = params[:organization][:name]
    @organization.address = params[:organization][:address]
    @organization.website = params[:organization][:website]
    @organization.logo = params[:organization][:logo]
    @organization.description = params[:organization][:description]
    @organization.founded_in = params[:organization][:founded_in]
    @organization.submitter_email = params[:organization][:submitter_email]
    @organization.submitter_name = params[:organization][:submitter_name]
    @organization.category_id = params[:organization][:category_id]
    @organization.approved = false
    if @organization.save
      SubmissionMailer.thanks(@organization)
      render json: "success", status: 200
    else
      render json: "fail", status: 402
    end
  end

  def organization_form_submission
    @organization = Organization.new
    @organization.name = params[:name]
    @organization.address = params[:address]
    @organization.website = params[:website]
    @organization.logo = params[:logo]
    @organization.description = params[:description]
    @organization.founded_in = params[:founded_in]
    @organization.submitter_email = params[:submitter_email]
    @organization.submitter_name = params[:submitter_name]
    @organization.category_id = params[:category_id]
    @organization.approved = false
    if @organization.save
      SubmissionMailer.thanks(@organization)
      render json: "success", status: 200
    else
      render json: "fail", status: 402
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Startupsinmumbai
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/main/home.html.haml
!!!
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8">
/[if IE 8] <html class="no-js lt-ie9">
/ [if gt IE 8]><!
%html.no-js
  / <![endif]
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %title Startups in Mumbai
    %meta{:content => "", :name => "description"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    / Place favicon.ico and apple-touch-icon.png in the root directory
    %link{:href => "http://fonts.googleapis.com/css?family=Raleway:800,400", :rel => "stylesheet", :type => "text/css"}
    %link{:href => "http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css", :rel => "stylesheet"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    /[if lt IE 7]
      %p.browsehappy
        You are using an
        %strong outdated
        browser. Please
        %a{:href => "http://browsehappy.com/"} upgrade your browser
        to improve your experience.
    / Add your site or application content here
    #modal-1.md-modal.md-effect-10
      .md-content
        .submission-container
          .form-description
            %p Lend a hand in putting Aamchi Mumbai ahead in the startup game. Submit your information for review and be a part of the success!
          = form_for @organization, url: submission_path do |f|
            .half
              .form-group
                %label{:for => "website"} Your Name
                = f.text_field :submitter_name
              .form-group
                %label{:for => "website"} Your Email
                = f.email_field :submitter_email
                %span#mailcheck
              .form-group
                %label{:for => "category"} Category
                = f.select :category_id, Category.all.collect{|c| [c.name, c.id]}
              .form-group
                %label{:for => "name"} Name
                = f.text_field :name
            .half
              .form-group
                %label{:for => "description"} Description
                = f.text_field :description
              .form-group
                %label{:for => "logo"} Logo
                = f.file_field :logo
              .form-group
                %label{:for => "website"} Website
                = f.url_field :website
              .form-group
                %label{:for => "address"} Address
                = f.text_field :address
            .clearfix
            .cta-box
              %button{:type => "submit"} Submit
          .success-box
            %img{src: asset_path('tick.png'), :alt => "Tick", width: "60px"}
            %p Thanks for taking to the time and effort to make a submission. We will inform you once we’ve reviewed and added it to our list.
    #modal-2.md-modal.md-effect-10
      .md-content
        %div
          .center.about-image
            %img{alt: "About Startups in Mumbai", src: asset_path('logo-large.png'), width: "300px"}
          %p We made this resource to help the startup commnunity in Mumbai to explore and connect with the right people. We've launched the map but we need your help to keep it flying. Not on the map? Fix that by submitting your information here. Together, we can enrich and grow the startup ecosystem of Aamchi Mumbai!
          .about-footer.center
            %p
              Made with love by
              %a{:href => "http://genii.in", :target => "blank" }
                %img{:alt => "Genii", src: asset_path('genii.png'), width: "40px"}
    .md-overlay
    %header
      .logo
        %img#logoClick{alt: "Startups in Mumbai", src: asset_path('logo.png'), width: "80%"}
      %nav
        %ul
          %li
            %a.first-button.md-trigger{"data-modal" => "modal-1", :href => "#"} Make a submission
          %li
            %a.second-button.md-trigger{"data-modal" => "modal-2", :href => "#"} About this project
          %li
            .search-container
              %input#searchField{:name => "search", :placeholder => "Search", :type => "text"}
              %span.search-clear
                %i.fa.fa-times

    %section
      #map
      .listing
        .listing-inner
          %ul
            %li
              %span#startupsButton
                %i.fa.fa-lightbulb-o
                Startups
                (
                %span#startupsCount
                )
              .content
                %ul#startupsList
            %li
              %span#investorsButton
                %i.fa.fa-rupee
                Investors
                (
                %span#investorsCount
                )
              .content
                %ul#investorsList
            %li
              %span#acceleratorsButton
                %i.fa.fa-line-chart
                Accelerators
                (
                %span#acceleratorsCount
                )
              .content
                %ul#acceleratorsList
            %li
              %span#incubatorsButton
                %i.fa.fa-leaf
                Incubators
                (
                %span#incubatorsCount
                )
              .content
                %ul#incubatorsList
            %li
              %span#coworkingButton
                %i.fa.fa-user
                Co-working spaces
                (
                %span#coworkingCount
                )
              .content
                %ul#coworkingList
      .clearfix
    %script{src: "https://maps.googleapis.com/maps/api/js?key=AIzaSyA52pI2ePsZMPpyYB91F2ev5vJWdYatkrQ", type: "text/javascript"}
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-26353814-4', 'auto');
      ga('send', 'pageview');